### ISSUE TITLE
Mapear , definir e documentar entidades e api's

### ISSUE THREAD

**Issue by vzsoares** [podcodar/voting-system#10]
Devemos criar uma forma inteligente de mapear nossa API, uma possibilidade seria utilizar o swagger, um exemplo de biblioteca seria o https://github.com/jellydn/next-swagger-doc.

Vamos tentar levantar o melhor modo de documentarmos nossa api.

ao fim desta implementação , necessário também adicionar junto ao desenho dos fluxos este mapeamento.

TODO

- [ ] [Prisma](https://www.prisma.io/)
- [ ] [tRPC](https://trpc.io/docs/nextjs) / [tRPC-openapi](https://github.com/jlalmes/trpc-openapi)
- [ ] [swagger](https://swagger.io/)?
- [ ] desenhar entidades no flow chart

**Comment by vzsoares** [comment]
utils
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#other-supported-patterns

**Comment by vzsoares** [comment]
@frattezi tive erro de type no passo # 5 do [trpc](https://trpc.io/docs/nextjs#5-configure-_apptsx) creio q tem a ver com o `withProviders` pq quando tirei ate passou nos tipos . [Branch](https://github.com/podcodar/voting-system/tree/vzsoares/feat/trpc) que estou testando

**Comment by frattezi** [comment]
Massa mano, no mexi num prisma aqui até emocionei, vo fazer um test aqui
