### ISSUE TITLE
Adicionar uma forma de finalizar a votação

### ISSUE THREAD

**Issue by vzsoares** [podcodar/voting-system#11]
É necessário, na tela de votação, fornecer uma forma do professor encerrar uma eleição. Acredito que um botão com menu deslizante discreto no canto superior da página seja suficiente.

Ao fazer isto, a aplicação deve mover o usuário para a rota: `/result?electionId`. 

![Image](https://user-images.githubusercontent.com/14007745/178852778-cb477381-92a2-4037-914f-c66abaddf268.png)

Até o momento, pensamos em um menu discreto no canto da tela, onde o professor irá inserir uma senha e com isto ser redirecionado para página de resultados!

**Comment by frattezi** [comment]
Esta task também está na board de design da Maíra, pode ser interessante conversar com ela antes, coletar idéias, pensar um design,

Você poderá ir adiantando a funcionalidade caso o visual não esteja completamente pronto no figma.

**Comment by Joel-leal** [comment]
Não seria interessante essa votação ser fechada automaticamente depois de um certo tempo? Penso que se optarmos por colocar um botão precisamos de autenticação do professor para que isso não seja feito por qualquer estudantes ou pessoa. Não esotu bem certo disso, por isso a sugestão do tempo.

**Comment by vzsoares** [comment]
e se a gente colocar uma combinação secreta no input ? '-'

**Comment by Joel-leal** [comment]
Acredito que pode fazer sentido sim @vzsoares
