### ISSUE TITLE
Adicionar o painel de instruções abaixo no visor, indicando as ações possíveis pro usuário

### ISSUE THREAD

**Issue by frattezi** [podcodar/voting-system#45]
Adicionar o painel de instruções aqui:

![Image](https://user-images.githubusercontent.com/14007745/193417346-3a7e7484-8fd8-468d-95d7-22698a5fb310.png)

Seguir o fluxo do [simulador](https://www.tse.jus.br/hotsites/simulador-de-votacao/depFederal.html):

![Image](https://user-images.githubusercontent.com/14007745/193417378-ec9bb91c-a9b1-4bf7-a897-78737cfc22d9.png)

**Comment by frattezi** [comment]
@vzsoares essa aqui já foi junto no #48  não?

**Comment by vzsoares** [comment]
> @vzsoares essa aqui já foi junto no #48 não?

sim!
