### ISSUE TITLE
Criar middlewares de verificação de body e params para rotas

### ISSUE THREAD

**Issue by vzsoares** [podcodar/voting-system#7]
Hoje, na API next não fazemos nenhum tipo de verificação nem do body ou dos paramêtros de URL da requisção. É necessário definir um tipo de schema para API (este schema pode ser compartilhado entre API e cliente). Quando uma nova requisição  for feita, o middleware irá verificar se os dados estão em conformidade com schema, em caso positivo, deverá seguir com a request, quando houverem errors, retornar a request em um status adequado e com uma mensagem descritiva, indicando os campos com erro.

**Comment by vzsoares** [comment]
related to #10

**Comment by frattezi** [comment]
Dado novos acertos do time. Vamos encerrar esta task sem validar o endpoint de post em `/api/elections/result`. Sendo este débito transferido para uma nova task.
